# Generated by Django 5.0.1 on 2024-01-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='nem',
            new_name='name',
        ),
    ]
